### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by ozooxo** [HaveIBeenPwned/PwnedPasswordsCloudflareWorker#15]
Notice that this worker is calling the API `/range` endpoint https://github.com/HaveIBeenPwned/PwnedPasswordsCloudflareWorker/blob/281231af5a0b59f1aef92c0798d871e44e4f7dd3/src/index.ts#L49

Does using this worker support an API key? Or since haveibeenpwned is hosted in Cloudflare, using this worker can bypass the rate limiting constrain?

**Comment by troyhunt** [comment]
There is no API key and no rate limit.
